// Image exports
export { default as BottleImage } from './bottle.png'
export { default as CollectBgImage } from './collect-bg.png'
export { default as FlashImage } from './flash.png'
export { default as FriendsImage } from './friends.png'
export { default as HeartImage } from './heart.png'
export { default as HomeBgImage } from './home-bg.png'
export { default as HomeImage } from './home.png'
export { default as MusicImage } from './music.png'
export { default as ShopImage } from './shop.png'
export { default as SpinImage } from './spin.png'
export { default as TaskImage } from './task.png'
export { default as UkFlagImage } from './uk-flag.png'
export { default as ShopBgImage } from './shop-bg.png'
export { default as ImmuneImage } from './immune.png'
