export { default as LevelOneBackgroundImage } from './level-1.png'
export { default as CyanSnowBackgroundImage } from './cyan-snow.png'
export { default as TealSnowBackgroundImage } from './teal-snow.png'
export { default as LeaderboardBackgroundImage } from './leaderboard.png'
export { default as PopupBackgroundImage } from './popup.png'
